server:
  port: 8000
spring:
  application:
    name: Ferry-consul
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: ferry-consul
# 开放健康检查接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS