spring:
  ####### Redis Config #######
  redis:
    database: 5
    # Redis服务器地址
    host: 1.116.227.4
    # Redis服务器连接端口
    port: 6379

  ####### redis缓存服务配置 #######
  session:
    store-type: redis

  ####### 自定义配置 #######

  ####### 自定义配置 #######
