spring:
  ####### Redis Config #######
  redis:
    database: 5
    # Redis服务器地址
    host: 1.116.227.4
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
#    password: qwe!@#123

  ####### redis缓存服务配置 #######
  session:
    store-type: redis

  ####### 自定义配置 #######
ai:
  appId: 17007424
  apiKey: ZPbvEmEhAtvdnOIG1BKadp4P
  secretKey: Lq2K2TD9reez1Ifsn9VCbn8zsfrNlMmv
  imageType: BASE64
  groupId: itcast
qr:
  url: http://localhost:8080/#/facelogin
  ####### 自定义配置 #######
