server:
  port: 8006
spring:
  application:
    name: Ferry-gossip
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: Ferry-gossip	# 注册到consul的服务名称
  boot:
    admin:
      client:
        url: "http://localhost:8000"
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ferryman?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: root
      password: root
      filters: stat,wall,log4j,config
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
  data:
    mongodb:
      uri: mongodb://hcz:hcz123456@1.116.227.4:27017/?authSource=admin&authMechanism=SCRAM-SHA-1
      database: ferryGossip
    redis:
      host: 1.116.227.4
      port: 6379
# 开放健康检查接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
#3600000 1h
jwt:
  config:
    key: ferry
    ttl: 36000000