server:
  port: 8003
spring:
  application:
    name: Ferry-web
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: Ferry-web	# 注册到consul的服务名称
  boot:
    admin:
      client:
        url: "http://localhost:8000"
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://1.116.227.4:3306/ferryman?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: root
      password: huangchongzhe
      filters: stat,wall,log4j,config
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
  data:
    mongodb:
      uri: mongodb://hcz:hcz123456@1.116.227.4:27017/?authSource=admin&authMechanism=SCRAM-SHA-1
      database: ferryGossip
      option:
        min-connection-per-host: 0
        max-connection-per-host: 100
        threads-allowed-to-block-for-connection-multiplier: 5
        server-selection-timeout: 30000
        max-wait-time: 120000
        max-connection-idle-time: 60000
        max-connection-life-time: 0
        connect-timeout: 10000
        socket-timeout: 60000
        socket-keep-alive: true
        ssl-enabled: false
        ssl-invalid-host-name-allowed: false
        always-use-m-beans: false
        heartbeat-socket-timeout: 20000
        heartbeat-connect-timeout: 20000
        min-heartbeat-frequency: 500
        heartbeat-frequency: 10000
        local-threshold: 15
# 开放健康检查接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
#3600000 1h
jwt:
  config:
    key: ferry
    ttl: 36000000