server:
  port: 8020
spring:
  application:
    name: Ferry-config
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: Ferry-config	# 注册到consul的服务名称
    config:
      label: master  # git仓库分支
      server:
        git:
          uri: https://gitee.com/chongzhe/Ferry-config.git
          username: 账号
          password: 密码
  rabbitmq:
    addresses: 1.116.227.4
    username: guest
    password: guest
    cache:
      channel:
        size: 25
    port: 15672
management:
  endpoints:
    web:
      exposure:
        include: "*"